{
 "title": "Sales - Total Created",
 "tags": [
  "sales",
  "business",
  "micrometer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total de Vendas Criadas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sales_created_total{application=\"sales-service\"}"
    }
   ]
  },
  {
   "title": "Total de Vendas Contratadas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sales_contracts_activated_total{application=\"sales-service\"}"
    }
   ]
  },
  {
   "title": "Total de Vendas Contratadas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sales_contracts_activated_total{application=\"sales-service\"}"
    }
   ]
  },
  {
   "title": "Taxa de Vendas por hora",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sales_created_total{application=\"sales-service\"}[1h])"
    }
   ]
  },
  {
   "title": "Taxa de Vendas Contratadas por hora",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(sales_contracts_activated_total{application=\"sales-service\"}[1h])"
    }
   ]
  }
 ]
}